language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
# command to install dependencies
before_install:
- sudo apt-get update -qq
install:
  - pip install -r requirements.txt
before_script:
- sudo apt-get install -qq python-smbc
# command to run tests
script: python smbscanner.py -h
