language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get update -qq && sudo apt-get install -qq python-smbc
# command to run tests
script: python smbscanner.py -h
